### ISSUE TITLE
Keep track of the active tab in the navbar menu

### ISSUE THREAD

**Issue by GnosisAssembler** [vyper-protocol/vyper-otc-ui#120]
Create a utility function to keep track of the **active** tab in the navbar menu (TopBar).

The active tab, should have **darker** color, when hovered or active.

Also fix the styling issue with the `font-weight`, in the **home** item.

![fix](https://user-images.githubusercontent.com/37915310/194110719-75e3051f-6907-4213-ac0c-c288a2713e36.png)

**Comment by thegreat-vanderlinde** [comment]
Let's include in this issue also the correct center-alignment of the nav buttons with the search bar
