### ISSUE TITLE
Create contract preview card

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#125]
We need to create a contract preview card to use in the explorer page, it will have a subset of information than the summary page, but enough to allow user to understand the current state of the contract.
This card will be used to show contracts fetched from DB in the explorer page, the high level process will be something like:
1. fetch contracts public keys from db
2. fetch contracts data onchain for all the pubkeys
3. render a preview card per each contract

In a separated issue we'll take care also of filters to conditionally fetch contracts (for example: fetch only open contracts, fetch single side funded contracts, etc...)

Regarding the behavior:
- once the user hover the mouse on a card it increases the [elevation](https://evergreen.segment.com/foundations/layers#elevation_styles)
- once the user click on the card it navigates on the summary page

CC @vantessel for feedbacks on the preview details to show

**Comment by vantessel** [comment]
In order of importance

1. Underlying (e.g. SOL_USD)
2. Contract type (e.g. Forward)
3. Contract status (e.g. Active)

For forward contracts

1. Notional
2. Strike
3. Expiry

All these info may make the card  a bit crowded, maybe we can start with showing only some and then in the future add more info only on hover?

**Comment by thegreat-vanderlinde** [comment]
> All these info may make the card a bit crowded, maybe we can start with showing only some and then in the future add more info only on hover?

Increasing component contents on hover is usually a UX bad practice. 

Let's try to include all the suggested info in a first draft and we'll review it in the deploy preview.

For
- Contract type (e.g. Forward)
- Contract status (e.g. Active)

we should try to re-use the same component (`Badge`) used in the summary page for consistency.
