### ISSUE TITLE
Move notification to the bottom of the screen

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#130]
Currently we have notification appearing in the top center screen area. This is annoying as they overlap the top navbar.

Move standard notification location to the bottom of the screen.
Forbidden area is the right bottom corner, as it will be reserved for transaction handler notifications, see #129

**Comment by vantessel** [comment]
Maybe from UX point of view would be weird to have certain notifications on bottom left and some others on bottom right?

**Comment by thegreat-vanderlinde** [comment]
True, the problem is that for tx handling rn we can't use the evergreen (current design system) notifications, so in any case there will be notifications with different appearances. Eventually we can evaluate to merge all notifications (both standard and tx-related) under the same notification library, in that case will be easier to have all of them appearing in the same location with the same look. 

In other projects we used [notistack](https://notistack.com/) probably a standard for react, we can evaluate also different libraries.

**Comment by vantessel** [comment]
I see, then we can probably wait and add tx handling notifs only when we are ready to merge them? That way we can avoid the intermediate step of two different notification systems on the same UI
