### ISSUE TITLE
Hovering the claim button not always working

### ISSUE THREAD

**Issue by solbricklayer** [vyper-protocol/vyper-otc-ui#143]
When I hover over the claim button, the button is not always clickable (sometimes I see the hand and sometimes only the arrow)

See attached video

https://user-images.githubusercontent.com/67789073/194748621-bbaeb1f8-2cdf-48e3-90ac-8e00d87c11a8.MOV

**Comment by sudoshreyansh** [comment]
The footer is overlapping with the claim button, which causes the issue.
Related to #79
