### ISSUE TITLE
add currencies to dropdown in create contract

### ISSUE THREAD

**Issue by solbricklayer** [vyper-protocol/vyper-otc-ui#169]
add to the list:

- USDC: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
- SOL: 11111111111111111111111111111111
- wSOL: So11111111111111111111111111111111111111112

**Comment by thegreat-vanderlinde** [comment]
Include those mint in this list:

https://github.com/vyper-protocol/vyper-otc-ui/blob/838dae506660d051474c177d3eaaf15000a7a7b3/src/pages/contract/create/index.tsx#L182-L191

in the label can be useful to specify the cluster, like `mainnet USDC` for example
