### ISSUE TITLE
PnL update with rate updates

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#185]
Even if the oracle gets updated frequently, the PnL doesn't until a page refresh. We should have that every "current price" update triggers a PnL update

**Comment by GnosisAssembler** [comment]
Consider moving the PNL logic inside `RedeemLogicForwardState`

**Comment by thegreat-vanderlinde** [comment]
this is blocked by #127 where we introduced the redeem logic plugin abstraction, will take care of this as soon as the simulator is merged on `dev`
