### ISSUE TITLE
reserve mint default value

### ISSUE THREAD

**Issue by solbricklayer** [vyper-protocol/vyper-otc-ui#205]
- put default USDC mainnet
- remove mainnet test token

![Uploading Screenshot 2022-10-18 at 15.25.12.png…]()

**Comment by thegreat-vanderlinde** [comment]
@GnosisAssembler remove these lines:
https://github.com/vyper-protocol/vyper-otc-ui/blob/dev/src/pages/contract/create/index.tsx#L185-L188
