### ISSUE TITLE
New API endpoint for fetching token info by symbol

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#231]
Currently we have a Next.js API endpoint that, taken a token mint, returns the token infos: symbol, name, image and address.

https://github.com/vyper-protocol/vyper-otc-ui/blob/93511228aaac04860d12647b1878522c91f68a70/src/pages/api/token-info.ts#L9-L26

We're gonna need to support this kind of research also by the token symbol. 

So, for example, both these requests should return the same result:
https://otc.vyperprotocol.io/api/token-info?mint=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
https://otc.vyperprotocol.io/api/token-info?symbol=USDC

(right now only the first one works)

**Comment by Shikhar15606** [comment]
Hi @thegreat-vanderlinde, why are we having 2 separate fetch methods namely `fetchTokenInfoFromMetaplex` and `fetchTokenInfoFromSolanaProvider` is one fetch method not sufficient ?

https://github.com/vyper-protocol/vyper-otc-ui/blob/93511228aaac04860d12647b1878522c91f68a70/src/pages/api/token-info.ts#L28

https://github.com/vyper-protocol/vyper-otc-ui/blob/93511228aaac04860d12647b1878522c91f68a70/src/pages/api/token-info.ts#L50

Also I was thinking of adding a similar check for the symbol like this in the `fetchTokenInfoFromSolanaProvider` function. 
https://github.com/vyper-protocol/vyper-otc-ui/blob/93511228aaac04860d12647b1878522c91f68a70/src/pages/api/token-info.ts#L55-L57

But for the `fetchTokenInfoFromMetaplex` function i am still unsure what to do. Also is there a well defined documentation for `@metaplex-foundation/js` coz all i got was their readme file.

**Comment by thegreat-vanderlinde** [comment]
> is one fetch method not sufficient ?

Definitely no. Please check the conversation on this old issue #110 closed with #145 

> Also is there a well defined documentation for `@metaplex-foundation/js` coz all i got was their readme file.

Here's some docs from metaplex https://docs.metaplex.com/

For this issue, fetching token info from symbol, we can just skip metaplex metadata method and fetch just with the old method, token-provider
