### ISSUE TITLE
Replace Evergreen UI with MUI

### ISSUE THREAD

**Issue by GnosisAssembler** [vyper-protocol/vyper-otc-ui#263]
We should move all codebase from using Evergreen tags & components, entirely to MUI components.

**Comment by stevenhansel** [comment]
As I refactor the components, I will try also to make the Story of each component that gets refactored (Storybook)

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel @sudoshreyansh @Shikhar15606 I've opened a new branch https://github.com/vyper-protocol/vyper-otc-ui/tree/mui-migration let's use that for this issue, so we can open a single PR from there and check all the portings at once. I'm going to close the existing PRs, can you please port your work on the new branch?

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde I just ported my work
