### ISSUE TITLE
Simulator - use collateral amount and not collateral deposit

### ISSUE THREAD

**Issue by solbricklayer** [vyper-protocol/vyper-otc-ui#288]
if I use collateral deposited, I can't see the simulator until the collateral amount gets deposited

example here:
<img width="615" alt="Screenshot 2022-10-31 at 14 23 58" src="https://user-images.githubusercontent.com/67789073/199030909-62e9fce0-3613-4389-b293-4d7f8aeeb9a1.png">

better to switch to collateral so the simulator works in ever circumstance

**Comment by vantessel** [comment]
Just checked and this should be fixed by https://github.com/vyper-protocol/vyper-otc-ui/pull/276 not in prod yet
