### ISSUE TITLE
Wrong rendering in Explorer

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#290]
It seems that the latest update in the asset rendering is creating some bugs:

prod
![image](https://user-images.githubusercontent.com/19397409/199068405-f822d422-a67e-44f8-9c46-cea5ecbbc7ff.png)

staging
![image](https://user-images.githubusercontent.com/19397409/199068316-5a5a4f8a-bc5a-458d-a47c-3e7ec94fff66.png)

**Comment by thegreat-vanderlinde** [comment]
Related to #292

**Comment by thegreat-vanderlinde** [comment]
fixed with #292
