### ISSUE TITLE
Stop listening for ws prices if contract is settled

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#291]
In the contract summary component we're listening for prices changes, this is useful only if the contract is not settled. 

https://github.com/vyper-protocol/vyper-otc-ui/blob/c63b84489ff1685c81f507b1bfeb498b11f36a7a/src/components/organisms/ChainOtcStateDetails/ChainOtcStateDetails.tsx#L49-L52

In case the contract is settled we need to remove the listener.

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde I was thinking to return a listener remover function from the react hook ```useOracleLivePrice``` and call it in the ```ChainOtcStateDetails``` when the contract is not settled.

**Comment by Shikhar15606** [comment]
To fix this issue i first need to fix this #310
