### ISSUE TITLE
Explorer filters in the URL

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#312]
Currently the explorer fetch contracts from database using an hardcoded query:
https://github.com/vyper-protocol/vyper-otc-ui/blob/25a69656e2ec4283563c8c748d76d7272e97caa8/src/controllers/fetchContracts/FetchContractsParams.ts#L15-L25
Once the contracts are fetched we can sort and filter data using the MUI datagrid.

We have to move sorting and filters in the explorer url so users will be able to share it recreating the same contracts set.

Currently the database columns that we can use for filters / sorting are:
```sql
select table_name,
       column_name,
       data_type
from information_schema.columns
where table_name = 'contracts'
order by ordinal_position;
```
| table_name | column_name                        | data_type                |
| ---------- | ---------------------------------- | ------------------------ |
| contracts  | pubkey                             | character varying        |
| contracts  | reserve_mint                       | character varying        |
| contracts  | buyer_deposit_amount               | bigint                   |
| contracts  | seller_deposit_amount              | bigint                   |
| contracts  | redeem_logic_plugin_type           | character varying        |
| contracts  | redeem_logic_plugin_data           | json                     |
| contracts  | rate_plugin_type                   | character varying        |
| contracts  | rate_plugin_data                   | json                     |
| contracts  | created_at                         | timestamp with time zone |
| contracts  | deposit_available_from             | timestamp with time zone |
| contracts  | deposit_expiration_at              | timestamp with time zone |
| contracts  | settle_available_from              | timestamp with time zone |
| contracts  | tranche_config_pubkey              | character varying        |
| contracts  | redeem_logic_plugin_program_pubkey | character varying        |
| contracts  | redeem_logic_plugin_state_pubkey   | character varying        |
| contracts  | rate_plugin_program_pubkey         | character varying        |
| contracts  | rate_plugin_state_pubkey           | character varying        |
| contracts  | cluster                            | character varying        |

Before submitting the query we have to check (and eventually fix):
- `cluster` can't be manipulated by the users, on mainnet we fetch mainnet contracts, same for devnet
- `redeem_logic_plugin_type` and `rate_plugin_type` have to match with one or more form the the current supported plugin types. We already have this check here:
https://github.com/vyper-protocol/vyper-otc-ui/blob/25a69656e2ec4283563c8c748d76d7272e97caa8/src/api/supabase/selectContracts.ts#L23-L25

**Comment by thegreat-vanderlinde** [comment]
If needed we can grant read-only access to the supabase backend for better checking the tables struct

**Comment by stevenhansel** [comment]
Just to make sure before I start working. Essentially you want to make the filters in the explorer page to be also in the URL Query Params is it? @thegreat-vanderlinde

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel extactly, this will help share a _view_ in the explorer. for example when I'm done with all the filtering and sorting I can share with you the URL containing all the queryparams and you can replicate the same search just browsing it. Please be aware that as of now a lot of parameters that we currently show in the explorer grid are fetched after the database query, so for now we can skip it. We'll nee in the url just the field reported above
