### ISSUE TITLE
Contract cloning

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#315]
We'll need a contract cloning logic where users can clone the parameters from an existing contract.

The flow could be something similar to:
1. user select a "clone" action on an existing contract (nested in a contextual menu - three dots menu ie)
2. all the static parameters are read and shared with the contract creation page.
 
We can develop the latter point in multiple ways:
- use the browser `localStorage` / `sessionStorage` to share data: on the summary page we add data to a temp variable then we navigate on the creation page where some logic on page mount can check if the temp data is present and place values in the inputs (and remove from the temp storage)
- we can place temporary values in the url, navigate to the creation url with all the params and then read them.
- others solutions are possible
 
Probably the best/simplest option is the first one.

**Comment by thegreat-vanderlinde** [comment]
`sessionStorage` vs `localStorage` vs other browser persistence system doesn't change a lot, it's more a matter of style I guess. Remember that when we arrive in the create contract page the first thing after the page mount is to check it the temp object is present and then _comsume_ it removing from the storage (having the object persisted across closed tabs it's something we can avoid: it's not useful and can just lead to users misunderstanding).

> I am thinking of adding a `sessionStorageHelper.ts` that has a helper functions. One helper function takes an object and saves it in the `sessionStorage`. The other helper function will check for the object and fetches it if present.

Building helper function is always a good practice, usually makes sense if we have some logic to wrap in a dedicated method in order to re-use it.

This is a super cool library we can use for this issue, having it in the project can surely be helpful also in the future:
https://github.com/pmndrs/zustand 
Please give it a look and let me know your thoughts

**Comment by thegreat-vanderlinde** [comment]
@Shikhar15606 FYI, @vantessel is refactoring the contract create page, probably there'll be some changes. If you still can decide where to start probably starting from the contract side and taking care of the storage is better in order to avoid too much conflicts

**Comment by Shikhar15606** [comment]
[zustand](https://github.com/pmndrs/zustand) is amazing. It will make the issue much simpler, we can simply store/retrieve the state with minimal code. I think we should use it. Thanks for letting me know about it.

Shall I wait for the mui migration pr to get merged ??

**Comment by thegreat-vanderlinde** [comment]
I think you can already start with the underlying logic, then you can move on the UI as soon as the MUI porting is completed
