### ISSUE TITLE
Contracts template

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#316]
Contracts templates are special boxes (cards) that users can select to fill the contract creation page and speed up the creation process, literally 2-clicks.

The boxes will be placed in the homepage with a gallery/carousel look and feel. Each box will show the template information and is clickable. The available templates are static and provided from a json file in the project.

Currently the object used as input for the creation page is:
https://github.com/vyper-protocol/vyper-otc-ui/blob/25a69656e2ec4283563c8c748d76d7272e97caa8/src/controllers/createContract/OtcInitializationParams.ts#L4-L31
So the template object will need to match that.

Please note that of course providing timestamps for `depositStart`, ` depositEnd` and `settleStart` in the template doesn't make sense, so we'll use intervals. In the template we'll store those informations as _milliseconds from now_, once the template is selected we calculate the timestamps from those intervals.

In order to share information from the template and the creation page please see discussion in #315

**Comment by vantessel** [comment]
Can be in the form of carousel or even a static grid, something like here: https://www.matcha.xyz/

**Comment by vantessel** [comment]
switchboard also has templates: https://app.switchboard.xyz/template/50619d7e-4b1b-4869-8831-94aa39e42ecc

**Comment by vantessel** [comment]
to separate the issues, let's keep here the handling of the `ContractTemplate` (i.e. from an object to the `create` paged already filled). The graphical part we do it in #379
