### ISSUE TITLE
Add a trollbox

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#318]
We'll inlcude a trollbox (chat room with online users) in the website, surely there's plenty of ready-to-use solutions. We have to do some research and include it

**Comment by stevenhansel** [comment]
Hey, @thegreat-vanderlinde I think a wrapped XMPP Server would be nice, I did a little bit of research and https://snikket.org/service/ is open source.

For connecting to Snikket's XMPP Server, we can use a xmpp client library like https://github.com/conversejs/converse.js or https://github.com/nioc/xmpp-web

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel that's a good idea, thanks! By the way as of now we can give lower priority to this compared to other issues, if you already started writing code please put it temporarily on hold
