### ISSUE TITLE
Improve contract create page

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#329]
As we move towards opening the contract create page to everyone, we should improve the workflow and UX so that external people can easily use it without too much prior knowledge.

**Comment by vantessel** [comment]
closed by #333 , will open more granular issues

**Comment by FedererKK** [comment]
up & down buttons should be consistent with value precision, for example DOGE and BTC ± 1$ result in a huge % difference

![image](https://user-images.githubusercontent.com/22641409/205983978-632089fe-f81f-4e77-a9f1-eb9a1fc15be3.png)
