### ISSUE TITLE
oracle explorer link

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#336]
Currently, in `ReservePicker` we show a button with a link to the explorer
![image](https://user-images.githubusercontent.com/19397409/202494662-0382ebd9-2427-4593-beff-505c35352135.png)

we should have the same for the `OraclePicker`. The link should direct to either the Switchboard or Pyth explorer. The added complexity is that Switchboard has predictable urls in the form of: https://switchboard.xyz/explorer/{networkID}/{aggregatorPubkey} 

while for pyth the URLs use the symbols, e.g. https://pyth.network/price-feeds/crypto-anc-usd?cluster=devnet

We could also consider adding the URL directly in the `oracles.json` to avoid issues

**Comment by thegreat-vanderlinde** [comment]
> We could also consider adding the URL directly in the `oracles.json` to avoid issues

+1 on this
