### ISSUE TITLE
Google Analytics tracking

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#36]
Add a GA tracking snippet. Using next js should be enough the standard snippet create on ga homepage, no custom react libraries.

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde shall I create the google analytics tag using my google account.

**Comment by thegreat-vanderlinde** [comment]
No no, we're going to provide you a script from vyper account. @solbricklayer can you create a new script for vyper otc ui website?

**Comment by solbricklayer** [comment]
Hello @Shikhar15606 - nice to meet you :) 

there we go with the code

`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Q7VRSL0DE3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Q7VRSL0DE3');
</script>`
