### ISSUE TITLE
improve decimal numbers formatting

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#380]
Currently the precision in `formatWithDecimalDigits` determines the significant digits using both the integer part and the decimal part. That is, using `4` as precision:

-  `1234.5678` is formatted as `1235`
- `12.345678` is formatted as `12.35`
- `0.12345678` is formatted as `0.1235`
- `0.0012345678` is formatted as `0.001235`

We should improve this behaviour and use `precision` to format a number of decimal digits, on top of any decimal leading zeros. The integer part should always be fully displayed, with `,` as thousands separator. So that, using again `4` as precision:

-  `1234.5678` is formatted as `1,234.5678`
- `12.345678` is formatted as `12.3457`
- `0.12345678` is formatted as `0.1235`
- `0.0012345678` is formatted as `0.001235`

Additionally we could even add a "jolly" precision, `-1`, to format only the thousands, and leave whichever number of decimals was there before:
- `1234.5678` is formatted as `1,234.5678`
- `1234567.8` is formatted as `1,234,567.8`
- `0.0012345678` is formatted as `0.0012345678`

Any leading integer or trailing decimal zeros should be removed i.e. `0012.3400` and `12.34` should have the same formatting.

**Comment by thegreat-vanderlinde** [comment]
For the formatting we can use the browser builtin `Intl.NumberFormat` (browser locale support). the decimal truncation is something we've to develop in-house instead

**Comment by sudoshreyansh** [comment]
@vantessel I have some test cases. Could you please tell what should be the output of these test cases?

- `123.000456`, precision = `2`
-  `123`, precision = `2`

**Comment by vantessel** [comment]
There you go:
* `123.000456`, precision = `2` should be formatted as `123.00`
* `123`, precision = `2`  should be formatted as `123.00`

For the sake of clarity:
> Any leading integer or trailing decimal zeros should be removed

This only refers to pre-formatting zeros, it is completely fine to have trailing zeros post-formatting
