### ISSUE TITLE
error in switchboard parsing

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#385]
in devnet explorer this error is always thrown

![image](https://user-images.githubusercontent.com/19397409/203868332-5b63e7b9-ef0f-4181-a67d-50c08bbcf941.png)

**Comment by thegreat-vanderlinde** [comment]
seems there's only one aggregator failing for this problem: https://staging.switchboard.xyz/explorer/2/67LiakUHxbPQQLBb4Nc3JLeFAcRKK6AbNYDSycMWuHYB 
will try to prevent that
