### ISSUE TITLE
Create a minimal landing page for the home page

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#39]
The home page must be minimal and clean with the following components:
- top bar with: logo, cluster selection, connect wallet button
- content with: text, search bar for browsing existing contracts, widget with the total number of contracts created (TBD)
- footer with social icons and copyright

**The home page must be single-screen tall: no scrolling** like [this](https://katana.so/).

Existing examples:
- https://katana.so/
- https://raydium.io/

**Comment by thegreat-vanderlinde** [comment]
As for now we can follow the [katana](https://katana.so/) style using a solid background (just one color) or try with an [abstract image](https://unsplash.com/s/photos/abstract).

**Comment by GnosisAssembler** [comment]
> The home page must be minimal and clean with the following components:
> 
>     * top bar with: logo, cluster selection, connect wallet button
> 
>     * content with: text, search bar for browsing existing contracts, widget with the total number of contracts created (TBD)
> 
>     * footer with social icons and copyright
> 
> 
> **The home page must be single-screen tall: no scrolling** like [this](https://katana.so/).
> 
> Existing examples:
> 
>     * https://katana.so/
> 
>     * https://raydium.io/

Some clarifications here:

- So the top bar should not have the current nav options (home, create-contract etc)?
- "widget with the total number of contracts created", do we need to discuss sth about that?
