### ISSUE TITLE
Light/Dark switcher

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#40]
We'll create a switchboard for the app theme. The selected theme value will be saved on browser local storage

Ref:
- [evergreen theming](https://evergreen.segment.com/introduction/theming)
- [example](https://jup.ag/)

**Comment by stevenhansel** [comment]
It seems that Evergreen doesn't have an official dark theme, there is [an issue](https://github.com/segmentio/evergreen/issues/1374) open, I think the effort is too big if we want to do it ourselves (as we have to color-pick one by one), but this is a good chance to contribute to Evergreen UI also, what do you think? @thegreat-vanderlinde

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel definitely a good chance to contribute to evergreen, but for now we can keep a lower priority for this. 

Please check the milestone v0.0.1 issues, those are the ones to go for the coming first live release

**Comment by thegreat-vanderlinde** [comment]
for now we can close this
