### ISSUE TITLE
Template contracs are not aligned on home

### ISSUE THREAD

**Issue by FedererKK** [vyper-protocol/vyper-otc-ui#404]
ETH/USD and its price are pushed to the bottom, probably by the "VANILLA OPTION" box taking two lines.

![image](https://user-images.githubusercontent.com/22641409/204504738-8b0fc3e3-92e3-499c-aa32-f1131754c761.png)

**Comment by vantessel** [comment]
which branch is this? the vanilla option is styled as a single word "vanilla_option", also "depeg" is not there anymore

**Comment by FedererKK** [comment]
https://deploy-preview-390--vyper-otc-devnet-stag.netlify.app/
