### ISSUE TITLE
Missing oracle URL when cloning

### ISSUE THREAD

**Issue by FedererKK** [vyper-protocol/vyper-otc-ui#439]
When cloning of a contract where the oracle is from Switchboard but not in default list (for example SBF-JAIL), 'View in Explorer' URL does not pickup the correct oracle address.

1. Search for contract 'CtoFqL4r7BDvG6zFZ2R8X4q2RSB5TQb1Gt4g3iqkprZX'
2. Click on 'Clone'
3. Click on 'View in explorer'

**Expected behavior**
Redirect correctly to https://switchboard.xyz/explorer/2/3DVLHvQSfTiU5EjswsQHr4MTNxtyaUFaWSshakQnKJoW in SBF-JAIL case or to the rightful oracle account

![image](https://user-images.githubusercontent.com/22641409/205160249-2e7e90ef-85c5-4d91-8637-2f4335a841cd.png)

**Comment by vantessel** [comment]
that's actually the expected behaviour, for external oracle (not mapped in the `oracles.json`) the explorer redirects to the general oracle explorer page. That's because for pyth it's harder to predict the exact url. For the popular ones, we can add them to the list of mapped oracles

**Comment by FedererKK** [comment]
I personally find it a bit confusing as it looks like a wrong redirect to the homepage. @solbricklayer wdyt?

**Comment by solbricklayer** [comment]
I think we can map the most popular ones and keep it simple. And as a reminder we will manually monitor the new contract which are created and add them to the json

**Comment by vantessel** [comment]
@FedererKK we can have this for SBF:
```
{
	"type": "switchboard",
	"cluster": "devnet",
	"pubkey": "3DVLHvQSfTiU5EjswsQHr4MTNxtyaUFaWSshakQnKJoW",
	"title": "SBF-TO-JAIL",
	"baseCurrency": "",
	"quoteCurrency": "",
	"explorerUrl": "https://switchboard.xyz/explorer/2/3DVLHvQSfTiU5EjswsQHr4MTNxtyaUFaWSshakQnKJoW"
}
```

**Comment by FedererKK** [comment]
> https://switchboard.xyz/explorer/2/3DVLHvQSfTiU5EjswsQHr4MTNxtyaUFaWSshakQnKJoW

Lgtm
