### ISSUE TITLE
Give more visibility to asset list

### ISSUE THREAD

**Issue by FedererKK** [vyper-protocol/vyper-otc-ui#450]
As some users requested, we should add more visibility to the amount and type of assets supported. Visualizing it in the 'index_stats_container' is a great move but I feel we can improve it further.

Couple of ideas:
- section in home page where we list the various asset categories
- separate page in the header

**Comment by thegreat-vanderlinde** [comment]
This is easy job, if it can help clarify things for users we can introduce it soon. Creating a dedicated section, either in homepage or a dedicated page, can let us also include a button for requesting new asset support.

**Comment by thegreat-vanderlinde** [comment]
working on it today. Probably a new section in the homepage is enough, wdyt? @FedererKK @vantessel

**Comment by vantessel** [comment]
agreed, we could use a marquee eg with https://www.react-fast-marquee.com/
