### ISSUE TITLE
Add Profit/Loss boxes in the Summary page

### ISSUE THREAD

**Issue by GnosisAssembler** [vyper-protocol/vyper-otc-ui#46]
When a contract is funded and the duration of the contract ends, we must add the profit or the loss, that user has sustained. 

An example would be:
![photo_2022-09-16_23-33-23](https://user-images.githubusercontent.com/37915310/190728410-925979bc-e769-47c6-888c-61645f0dc5a8.jpg)

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel this is already live

Closing this issue
