### ISSUE TITLE
abstract `Link` component

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#480]
We repeat in many places the link tag:
https://github.com/vyper-protocol/vyper-otc-ui/blob/a7dbbfc5140996b1ca36606bc39411517d02ea04/src/components/molecules/OraclesPicker/OraclesPicker.tsx#L183

we should create a `Link` component:
```typescript
interface LinkProps {
    href: string,
    openInNewWindow: boolean,
    disabled: boolean
}
```

**Comment by thegreat-vanderlinde** [comment]
we could use [this](https://nextjs.org/docs/api-reference/next/link)
