### ISSUE TITLE
explorer - filter DATE not working

### ISSUE THREAD

**Issue by solbricklayer** [vyper-protocol/vyper-otc-ui#492]
<img width="1361" alt="Screenshot 2022-12-13 at 21 47 34" src="https://user-images.githubusercontent.com/67789073/207440225-257badb1-c433-4216-abc8-399504da6038.png">

I should be able to see trades as they are here

<img width="1340" alt="Screenshot 2022-12-13 at 21 48 14" src="https://user-images.githubusercontent.com/67789073/207440319-865a171a-7980-47a7-b0f7-536461944860.png">

**Comment by thegreat-vanderlinde** [comment]
@solbricklayer can you please provide the wallet in the quick filter `9d1ko...`?

**Comment by solbricklayer** [comment]
`9d1ko1ZV8quBwi5C9HEAyJGb9QTSYJq2trznJ6nyfcbd`
