### ISSUE TITLE
Shorten text message when contract ios shared

### ISSUE THREAD

**Issue by FedererKK** [vyper-protocol/vyper-otc-ui#515]
the URL when we share a new trade (Telegram and others) takes lot of space too, how about closing with the following?

"Trade now 👉🏻 [LINK](https://staging.demo.otc.vyperprotocol.io/contract/summary/4o9NWYQCxVjD1gKH8ADMAbip7aHiKsUcnD4ugJzfxjQR)"

_Originally posted by @FedererKK in https://github.com/vyper-protocol/vyper-otc-ui/issues/509#issuecomment-1361691274_

**Comment by vantessel** [comment]
that would require to modify SNS and supabase configs to send different messages for TG vs twitter as twitter doesn't have markdown. I'd say no need for this now
