### ISSUE TITLE
add more 10x

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#523]
- create reusable component for 10x featured
- add featured BNB, MATIC, BTC, coffee

**Comment by FedererKK** [comment]
IMHO good to have the reusable component but it will be more useful in the future. 

At this point having the same contract in the top bar multiple times might be counter-productive (takes away user attention), and we are better off showcasing different types of derivatives.

Also, we can re-use the component fo the stablecoin depeg.
