### ISSUE TITLE
Remove components from next pages folder

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#53]
We currently have some components in the pages folder, for example
`pages/contract/summary/DepositButton.tsx`

This cause nextjs to create pages also for those components:
<img width="765" alt="Screenshot 2022-09-19 at 17 50 38" src="https://user-images.githubusercontent.com/91868385/191059426-12ea19b7-46f9-4c92-9f62-8d70b51f1fd0.png">

This is an unwanted behavior. We need to move components back in a dedicated place, eg in the root `/components/` folder

**Comment by GnosisAssembler** [comment]
@GnosisAssembler  I am addressing this issue in the refactor branch `50-refactor`, along with this issue https://github.com/vyper-protocol/vyper-otc-ui/issues/50. 

Should we close along with the issue #50?

**Comment by thegreat-vanderlinde** [comment]
let's close only this one, for #50 please open a PR
