### ISSUE TITLE
explorer shows LIVE incorrectly 

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-otc-ui#561]
![image](https://user-images.githubusercontent.com/19397409/211043243-4b83cea4-e057-444f-91e6-aa6bd9f2f65a.png)

**Comment by thegreat-vanderlinde** [comment]
this is not a bug in the UI, some contracts had stale data on database. in the summary page we're using chain data and in the explorer db data. browsing wrong contracts (or expanding explorer rows) triggered the sync and fixed the discrepancy.
