### ISSUE TITLE
Decouple SearchBar from TopBar

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#65]
We need to decouple the `SearchBar` component from the `TopBar`. 

While all the pages will probably require the `TopBar` sometimes having the search bar doesn't make sense, for example during the contract creation.

https://github.com/vyper-protocol/vyper-otc-ui/blob/1429e6569e26373a8f910e1146e7c04ddc4b0f13/components/organisms/TopBar/TopBar.tsx#L69

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel just read your comments on #93 

if @GnosisAssembler hasn't started yet working on this issue you can take it and finish the top bar work

**Comment by GnosisAssembler** [comment]
> @stevenhansel just read your comments on #93
> 
> if @GnosisAssembler hasn't started yet working on this issue you can take it and finish the top bar work

I have not started it yet.

**Comment by stevenhansel** [comment]
Okay, I will take on this issue then, I will make a separate PR for this issue. Thanks!

**Comment by thegreat-vanderlinde** [comment]
Closed by #103
