### ISSUE TITLE
Introduce browser logging library

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#67]
We need to evaluate the introduction of a browser logging library in order to have logging levels (info, debug, error, warn, etc) and a more standard formatting.
After a fast google search here a bunch of possibilities:
- https://github.com/debug-js/debug
- https://github.com/winstonjs/winston
- https://github.com/trentm/node-bunyan
- https://github.com/gajus/roarr

After some evaluation and team discussion we can introduce the selected one and refactor all current `console.log`

**Comment by GnosisAssembler** [comment]
Winston is a very good one

**Comment by thegreat-vanderlinde** [comment]
> Winston is a very good one

I've always used winston for node.js project, I've no experience using it on browser based projects

**Comment by thegreat-vanderlinde** [comment]
This seems cool https://sentry.io/

**Comment by stevenhansel** [comment]
I'll try using Sentry first
