### ISSUE TITLE
Dashboard DnD Structure

### ISSUE THREAD

**Issue by GnosisAssembler** [vyper-protocol/vyper-otc-ui#71]
For the future Dashboard, (example [Switchboard Dasboard](https://app.switchboard.xyz/template/aafff881-ef69-4867-bbda-cdf1ee83dc31)) during the **Contract Creation** process, we should figure out a smart and easy way for the user to create his desired contract. 

A drag and drop mechanism, where the user drops all the desired components into a workspace, might be a very nice gamified way of tackling this. 

We should consider these libraries:

- https://github.com/atlassian/react-beautiful-dnd
- https://github.com/react-grid-layout/react-draggable
- https://github.com/clauderic/dnd-kit

This definitely needs more discussion.

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel please put on hold this one, it has been created by error.

It's planned in the roadmap in probably a couple of months. Will unassign and close
