### ISSUE TITLE
Improve mobile responsiveness

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#77]
We need to improve mobile responsiveness

![image](https://user-images.githubusercontent.com/91868385/193331511-7efc9603-c5c4-49b0-9015-bf5078919601.png)

**Comment by thegreat-vanderlinde** [comment]
Components to improve:
- [ ] collapsed menu
- [ ] search bar
- [ ] Footer

We can create multiple PRs for each point or a single one, the assignee can choose. 

@GnosisAssembler do you have other points to integrate?

**Comment by GnosisAssembler** [comment]
> Components to improve:
> 
>     * [ ]  collapsed menu
> 
>     * [ ]  search bar
> 
>     * [ ]  Footer
> 
> 
> We can create multiple PRs for each point or a single one, the assignee can choose.
> 
> @GnosisAssembler do you have other points to integrate?

No i think that's all. Maybe also the **Wallet** button needs some tweaks.

**Comment by thegreat-vanderlinde** [comment]
Yes, wallet connection on mobile still has super friction. Let's try to add the connect wallet button in the collapsed menu and we'll try the UX with [phantom mobile](https://apps.apple.com/app/id1598432977).

In the meanwhile we can do also some research on how others projects manage mobile.

**Comment by sudoshreyansh** [comment]
Yeah @thegreat-vanderlinde due to some university workload, I wasn't able to complete the issue. But I am working on it.
