### ISSUE TITLE
Create contracts fetching from API

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#80]
We need to create a wrapper for API methods in order to fetch saved contracts.

This issue is blocked by #68

**Comment by Shikhar15606** [comment]
Hi @thegreat-vanderlinde,
I am interested to work on this issue, can you please specify the exact tasks that need to be completed as a part of this issue?

**Comment by thegreat-vanderlinde** [comment]
@Shikhar15606 we're currently introducing supabase in the project, but that process is not completed yet. As soon as we've finished introducing it we'll need to create some utility methods to fetch data from backend.
