### ISSUE TITLE
Fix wallet background

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-otc-ui#98]
Seems that with #93 we introduced a UI glicth for the wallet connection button

<img width="1535" alt="Screenshot 2022-10-04 at 11 05 10" src="https://user-images.githubusercontent.com/91868385/193781430-d5f58cb3-c20c-4274-bfe3-3b9056e29099.png">

**Comment by GnosisAssembler** [comment]
i have already fixed that issue in this PR #105

**Comment by GnosisAssembler** [comment]
@thegreat-vanderlinde This is already fixed with the merging of #105. We can close this.
